[package]
name = "rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tch = "0.14.0"
anyhow = "1.0"
csv = "1.3.0"
config = "0.13.1"
serde = "1.0.190"
